[package]
name = "eywa-pagination"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
axum = { workspace = true }
eywa-errors = { workspace = true }
